export const GET_LIST_START = '@GET_LIST_START';
export const GET_LIST_SUCCESS = '@GET_LIST_SUCCESS';
export const GET_LIST_FAIL = '@GET_LIST_FAIL';

export const UPDATE_LIST_START = '@UPDATE_LIST_START';
export const UPDATE_LIST_SUCCESS = '@UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_FAIL = '@UPDATE_LIST_FAIL';

export const UPDATE_PAXNAME_START = '@UPDATE_PAXNAME_START';
export const UPDATE_PAXNAME_SUCCESS = '@UPDATE_PAXNAME_SUCCESS';
export const UPDATE_PAXNAME_FAIL = '@UPDATE_PAXNAME_FAIL';

export const GET_PASSANGER_BYID_START = '@GET_PASSANGER_BYID_START';
export const GET_PASSANGER_BYID_SUCCESS = '@GET_PASSANGER_BYID_SUCCESS';
export const GET_PASSANGER_BYID_FAIL = '@GET_PASSANGER_BYID_FAIL';
